---
- name: check-set-parameters
  ansible.builtin.include_tasks: packetbeat-parameters.yml
  tags:
      - always

- name: include packetbeat.yml
  ansible.builtin.include_tasks: packetbeat.yml
  tags:
      - install

- name: include packetbeat-config.yml
  ansible.builtin.include_tasks: packetbeat-config.yml
  tags:
      - config

  #We always execute xpack as we may need to remove features
- name: include packetbeat-ssl.yml
  ansible.builtin.include_tasks: packetbeat-ssl.yml
  tags:
      - ssl

- name: flush handlers
  meta: flush_handlers

- name: Make sure packetbeat is started
  service: name=packetbeat state=restarted enabled=yes
  become: true
  when: pb_start_service
