---

- name: Include optional user and group creation.
  when: (ls_user_id is defined) and (ls_group_id is defined)
  include: packetbeat-optional-user.yml

- name: Include specific packetbeat
  include: packetbeat-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific packetbeat
  include: packetbeat-RedHat.yml
  when: ansible_os_family == 'RedHat'
