---
- name: check-set-parameters
  ansible.builtin.include_tasks: filebeat-parameters.yml
  tags:
      - always

- name: include filebeat.yml
  ansible.builtin.include_tasks: filebeat.yml
  tags:
      - install

- name: include filebeat-config.yml
  ansible.builtin.include_tasks: filebeat-config.yml
  tags:
      - config

  #We always execute xpack as we may need to remove features
- name: include filebeat-ssl.yml
  ansible.builtin.include_tasks: filebeat-ssl.yml
  tags:
      - ssl

- name: flush handlers
  meta: flush_handlers

- name: Make sure filebeat is started
  service: name=filebeat state=restarted enabled=yes
  become: true
  when: fb_start_service
