---
- name: Auditbeat-Main - check-set-parameters
  ansible.builtin.include_tasks: auditbeat-parameters.yml
  tags:
      - always

- name: Auditbeat-Main - include auditbeat.yml
  ansible.builtin.include_tasks: auditbeat.yml
  tags:
      - install

- name: Auditbeat-Main - include auditbeat-config.yml
  ansible.builtin.include_tasks: auditbeat-config.yml
  tags:
      - config

  #We always execute xpack as we may need to remove features
- name: Auditbeat-Main - include auditbeat-ssl.yml
  ansible.builtin.include_tasks: auditbeat-ssl.yml
  tags:
      - ssl

- name: flush handlers
  meta: flush_handlers

- name: Auditbeat-Main - Make sure auditbeat is started
  service: name=auditbeat state=restarted enabled=yes
  become: true
  when: ab_start_service
