---

- name: Auditbeat - Include optional user and group creation.
  when: (ls_user_id is defined) and (ls_group_id is defined)
  ansible.builtin.include_tasks: auditbeat-optional-user.yml

- name: Auditbeat - Include specific auditbeat
  ansible.builtin.include_tasks: auditbeat-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Auditbeat - Include specific auditbeat
  ansible.builtin.include_tasks: auditbeat-RedHat.yml
  when: ansible_os_family == 'RedHat'
