---

- name: Metricbeat - Include optional user and group creation.
  when: (ls_user_id is defined) and (ls_group_id is defined)
  ansible.builtin.include_tasks: metricbeat-optional-user.yml

- name: Metricbeat - Include specific metricbeat
  ansible.builtin.include_tasks: metricbeat-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Metricbeat - Include specific metricbeat
  ansible.builtin.include_tasks: metricbeat-RedHat.yml
  when: ansible_os_family == 'RedHat'
