---

- name: Include optional user and group creation.
  when: (ls_user_id is defined) and (ls_group_id is defined)
  include: metricbeat-optional-user.yml

- name: Include specific metricbeat
  include: metricbeat-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific metricbeat
  include: metricbeat-RedHat.yml
  when: ansible_os_family == 'RedHat'
